#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         0
bspc config window_gap         	 5 

bspc config focus_follows_pointer true



bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nitrogen --set-scaled ~/Pictures/Wallpapers/wp1933949-pixel-art-wallpapers.png
compton &

~/.config/polybar/launch.sh

